site_name: Conway 2027 – Výrobní manuál
site_description: Výrobní manuál pro modely Conway 2027
site_author: Hartje Production

theme:
  name: material
  language: cs
  palette:
    primary: "#0b4ea2"
    accent: "#009fe3"
  custom_dir: overrides

extra_css:
  - styles/extra.css

plugins:
  - search
  - include-markdown
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/
      cover: true
      toc_level: 2
      # seznam souborů pro PDF export
      include_pages:
        - modely/cairon-c-1-0/Montáž.md
        - modely/cairon-c-2-0/Montáž.md
        - modely/cairon-c-4-0/Montáž.md
        - modely/cairon-c-1-0-nexus-8-chain/Montáž.md
        - modely/cairon-c-2-0-b-800/Montáž.md
        - modely/cairon-c-2-0-b-rbn-600/Montáž.md
        - modely/cairon-c-2-0-b-rbn-800/Montáž.md
        - modely/cairon-c-4-0-b/Montáž.md
        - modely/cairon-c-4-0-b-rbn/Montáž.md
        - modely/cairon-s-2-0/Montáž.md
        - modely/cairon-s-3-0/Montáž.md
        
nav:

  - Obecné:
      - Specifikace: obecne/specifikace.md
      - Bezpečnost: obecne/bezpecnost.md
      - Nástroje: obecne/nastroje.md

  - Modely:
      - Cairon C 1.0:
          - Přehled: modely/cairon-c-1-0/index.md
          - Montáž: modely/cairon-c-1-0/Montáž.md
          - Kusovníky: modely/cairon-c-1-0/Kusovníky.md

      - Cairon C 2.0:
          - Přehled: modely/cairon-c-2-0/index.md
          - Montáž: modely/cairon-c-2-0/Montáž.md
          - Kusovníky: modely/cairon-c-2-0/Kusovníky.md

      - Cairon C 4.0:
          - Přehled: modely/cairon-c-4-0/index.md
          - Montáž: modely/cairon-c-4-0/Montáž.md
          - Kusovníky: modely/cairon-c-4-0/Kusovníky.md

      - Cairon C 1.0 Nexus 8 chain:
          - Přehled: modely/cairon-c-1-0-nexus-8-chain/index.md
          - Montáž: modely/cairon-c-1-0-nexus-8-chain/Montáž.md
          - Kusovníky: modely/cairon-c-1-0-nexus-8-chain/Kusovníky.md

      - Cairon C 2.0 B 800:
          - Přehled: modely/cairon-c-2-0-b-800/index.md
          - Montáž: modely/cairon-c-2-0-b-800/Montáž.md
          - Kusovníky: modely/cairon-c-2-0-b-800/Kusovníky.md

      - Cairon C 2.0 B RBN 600:
          - Přehled: modely/cairon-c-2-0-b-rbn-600/index.md
          - Montáž: modely/cairon-c-2-0-b-rbn-600/Montáž.md
          - Kusovníky: modely/cairon-c-2-0-b-rbn-600/Kusovníky.md

      - Cairon C 2.0 B RBN 800:
          - Přehled: modely/cairon-c-2-0-b-rbn-800/index.md
          - Montáž: modely/cairon-c-2-0-b-rbn-800/Montáž.md
          - Kusovníky: modely/cairon-c-2-0-b-rbn-800/Kusovníky.md

      - Cairon C 4.0 B:
          - Přehled: modely/cairon-c-4-0-b/index.md
          - Montáž: modely/cairon-c-4-0-b/Montáž.md
          - Kusovníky: modely/cairon-c-4-0-b/Kusovníky.md

      - Cairon C 4.0 B RBN:
          - Přehled: modely/cairon-c-4-0-b-rbn/index.md
          - Montáž: modely/cairon-c-4-0-b-rbn/Montáž.md
          - Kusovníky: modely/cairon-c-4-0-b-rbn/Kusovníky.md

      - Cairon S 2.0:
          - Přehled: modely/cairon-s-2-0/index.md
          - Montáž: modely/cairon-s-2-0/Montáž.md
          - Kusovníky: modely/cairon-s-2-0/Kusovníky.md

      - Cairon S 3.0:
          - Přehled: modely/cairon-s-3-0/index.md
          - Montáž: modely/cairon-s-3-0/Montáž.md
          - Kusovníky: modely/cairon-s-3-0/Kusovníky.md

  - Přílohy:
      - Utahovací Momenty: prilohy/tabulka-momentu.md
